name: Deploy to Cloudflare Pages

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: cd-pipeline
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
